Customize logic

diff --git a/.github/workflows/qmk_userspace_build.yml b/.github/workflows/qmk_userspace_build.yml
--- a/.github/workflows/qmk_userspace_build.yml
+++ b/.github/workflows/qmk_userspace_build.yml
@@ -4,13 +4,18 @@ on:
   workflow_call:
     inputs:
       qmk_repo:
-        description: "qmk_firmware repo to build against"
-        default: "qmk/qmk_firmware"
+        description: 'qmk_firmware repo to build against'
+        default: 'qmk/qmk_firmware'
         required: false
         type: string
       qmk_ref:
-        description: "qmk_firmware branch to build against"
-        default: "master"
+        description: 'qmk_firmware branch to build against'
+        default: 'master'
+        required: false
+        type: string
+      keymap_name:
+        description: 'keymap name to build with'
+        default: ${{ github.actor }}
         required: false
         type: string
 
@@ -19,61 +24,62 @@ permissions:
 
 jobs:
   build:
-    name: Build Userspace Firmware
+    name: Build ${{ inputs.keymap_name }} Firmware
     runs-on: ubuntu-latest
     container: qmkfm/base_container
 
     steps:
-      - name: Checkout Userspace
-        uses: actions/checkout@v3
-        with:
-          token: ${{ github.token }}
-          submodules: recursive
+    - name: Checkout Userspace
+      uses: actions/checkout@v4
+      with:
+        submodules: recursive
 
-      - name: Check if qmk_firmware exists
-        id: check_files
-        uses: andstor/file-existence-action@v2
-        with:
-          files: qmk_firmware
+    - name: Check qmk_firmware exists
+      id: check_files
+      uses: andstor/file-existence-action@v2
+      with:
+        files: qmk_firmware
 
-      - name: Checkout QMK Firmware
-        uses: actions/checkout@v3
-        if: steps.check_files.outputs.files_exists == 'false'
-        with:
-          token: ${{ github.token }}
-          path: qmk_firmware
-          repository: ${{ inputs.qmk_repo || 'qmk/qmk_firmware' }}
-          ref: ${{ inputs.qmk_ref || 'master' }}
-          submodules: recursive
+    - name: Checkout QMK Firmware
+      uses: actions/checkout@v4
+      if: steps.check_files.outputs.files_exists == 'false'
+      with:
+        path: qmk_firmware
+        repository: ${{ inputs.qmk_repo || 'qmk/qmk_firmware' }}
+        ref: ${{ inputs.qmk_ref || 'master' }}
+        submodules: recursive
+        fetch-depth: 1000 # This line should be removed once userspace support exists in QMK Firmware
 
-      - name: Install QMK CLI
-        run: |
-          python3 -m pip install --upgrade qmk
-          python3 -m pip install -r qmk_firmware/requirements.txt
+    - name: Install QMK CLI
+      run: |
+        python3 -m pip install --upgrade qmk
+        python3 -m pip install mpire
+        python3 -m pip install -r qmk_firmware/requirements.txt
 
-      - name: Configure QMK CLI
-        run: |
-          qmk config userspace_compile.parallel=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
-          qmk config user.qmk_home=$GITHUB_WORKSPACE/qmk_firmware
-          qmk config user.overlay_dir=$GITHUB_WORKSPACE
+    - name: Configure QMK CLI
+      run: |
+        qmk config mass_compile.parallel=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
+        qmk config user.qmk_home=$GITHUB_WORKSPACE/qmk_firmware
+        qmk config user.overlay_dir=$GITHUB_WORKSPACE
 
-      - name: Build
-        run: |
-          qmk userspace-compile -e DUMP_CI_METADATA=yes || touch .failed
-          # Generate the step summary markdown
-          ./qmk_firmware/util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
-          # Truncate to a maximum of 1MB to deal with GitHub workflow limit
-          truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
-          # Exit with failure if the compilation stage failed
-          [ ! -f .failed ] || exit 1
+    - name: Build
+      run: |
+        rm -rfdv qmk_firmware/**/${{ inputs.keymap_name || github.actor }}/*
+        qmk mass-compile -e DUMP_CI_METADATA=yes -km ${{ inputs.keymap_name || github.actor }} || touch .failed
+        # Generate the step summary markdown
+        ./qmk_firmware/util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
+        # Truncate to a maximum of 1MB to deal with GitHub workflow limit
+        truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
+        # Exit with failure if the compilation stage failed
+        [ ! -f .failed ] || exit 1
 
-      - name: Upload binaries
-        uses: actions/upload-artifact@v3
-        if: always() && !cancelled()
-        continue-on-error: true
-        with:
-          name: Firmware
-          path: |
-            *.bin
-            *.hex
-            *.uf2
+    - name: Upload binaries
+      uses: actions/upload-artifact@v3
+      if: always() && !cancelled()
+      continue-on-error: true
+      with:
+        name: Firmware-${{ inputs.keymap_name || github.actor }}
+        path: |
+          *.bin
+          *.hex
+          *.uf2
